name: Docker-CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    tags:
      - "*"

jobs:
  build:
    name: Docker-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF_NAME == main ]]; then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="$GITHUB_REF_NAME"
          fi
          echo ::set-output name=tag::${DOCKER_TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Pipenv lock
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: lock

      - name: Export requirements.txt
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: requirements > "requirements.txt"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sonarr_youtubedl:${{ steps.tag.outputs.tag }}
